name: music_genre_classification
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.10.11
 - pip
 - pip:
   - streamlit
   - pandas
   - numpy==1.21.6
   - lightGBM
   - librosa
   - pydub
   - pickle-mixin